fix: update Nordea cert
The root certificate for Nordea Web Services was updated by Nordea, and
starting from 2022-11-09, the old one no longer passes validation.
Service API calls to Nordea are currently failing with error

> Error: Signature key is not trusted

Obtained from Nordea's Testing / Web Services site:
http://web.archive.org/web/20221109103353/
https://www.nordea.fi/yritysasiakkaat/palvelumme/verkko-mobiilipalvelut/
testaus.html#tab=Web-Services

This one will expire 2036-04-04.